name: test

on:
  workflow_dispatch:

jobs:
  extract-app-keys:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - id: extract-keys
        run: |
          keys=$(yq e 'keys' apps.yml -o=json | jq -c '.')
          echo "keys=${keys}" >> "${GITHUB_OUTPUT}"
    outputs:
      apps: ${{ steps.extract-keys.outputs.keys }}

  app-keys-matrix:
    runs-on: ubuntu-latest
    needs: extract-app-keys
    strategy:
      matrix:
        app: ${{ fromJson(needs.extract-app-keys.outputs.apps) }}
    steps:
      - run: echo ${{ matrix.app }}
      - run: exit 0
      - run: echo aaa
      - run: echo bbb
